name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx build api
      
      - name: Install Nix 
      - run: brew install railwayapp/tap/nixpacks
      - run: nixpacks build ./dist/apps --name api

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install packages
        run: npx nx install --frozen-lockfile

      - name: Run tests
        run: npx nx test api

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          NIXPACKS_NX_APP_NAME: api
