name: Testing And Deploying
on: 
  push:
    branches: 
      - main
  pull_request:
  
jobs:
  run-npx-nx-build:
    name: Build Applications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: npx nx install and build the website
        run: |
          npm ci
          npm i
          npx nx build zondagschoolapp
          npx nx build api
          npx nx build neo4j-api
      
  run-npx-nx-test: 
    name: Run Tests
    runs-on: ubuntu-latest
    needs: run-npx-nx-build
    steps:
      - uses: actions/checkout@v3
      - run: | 
          npm install --force
          npm test api
      
  
  

