name: Testing And Deploying
on: 
  push:
    branches: 
      - main
  pull_request:
  
jobs:
  run-npx-nx-build:
    name: Build Applications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: npx nx install and build the website
        run: |
          npm ci
          npm i
          npx nx build zondagschoolapp
          npx nx build api
          npx nx build neo4j-api
      - uses: actions/upload-artifact@v3
        with: 
          name: zondagschoolapp
          path: "./dist/apps/zondagschoolapp"
      
  run-npx-nx-test: 
    name: Run Tests
    runs-on: ubuntu-latest
    needs: run-npx-nx-build
    steps:
      - uses: actions/checkout@v3
      - run: | 
          npm install --force
          npm test zondagschoolapp
          npm test api
          npm test neo4j-api
          
  netlify-deploy:
    name: Deploy Applications
    runs-on: ubuntu-latest
    needs: run-npx-nx-test
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: zondagschoolapp
          path: "./dist/apps/zondagschoolapp"
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with: 
          publish-dir: "./dist/apps/zondagschoolapp"
          production-branch: main
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      
  
  

